steps:
  #Build Docker Image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build','-t','gcr.io/flask-app-492709/flask-app','.']
  
  #Push Image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push','gcr.io/flask-app-492709/flask-app']
  
  #Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud 
    args: [
          'run','deploy','flask-app','--image','gcr.io/flask-app-492709/flask-app',
          '--region','asia-south1','--platform','managed','--allow-unauthenticated']
  
images:
  - 'gcr.io/flask-app-492709/flask-app'